#!/bin/sh

echo ===Generate testing data====
mkdir tests
for amount in 5000 10000 20000 50000 100000
do   
    for t in 1 2 3 4 5
    do 
        # random
        echo tests/$amount.noDupli.random.$t 
        seq $amount | sort -R > tests/$amount.noDupli.random.$t
        # sorted
        echo tests/$amount.noDupli.sorted.$t
        seq $amount | sort -n> tests/$amount.noDupli.sorted.$t
        # reverse
        echo tests/$amount.noDupli.reverse.$t
        seq $amount | sort -nr > tests/$amount.noDupli.reverse.$t
        # random
        echo tests/$amount.duplicates.random.$t
        ./randList  $amount | sort -R > tests/$amount.duplicates.random.$t
        # sorted
         echo tests/$amount.duplicates.sorted.$t
        ./randList  $amount | sort -n > tests/$amount.duplicates.sorted.$t
        # reverse
        echo tests/$amount.duplicates.reverse.$t
        ./randList  $amount | sort -nr > tests/$amount.duplicates.reverse.$t
    done
done
echo ===Generate Done====