#!/bin/sh

echo ===Generate intList testing time====
mkdir tests/time/
for amount in 5000 10000 20000 50000 100000
do   
    for t in 1 2 3 4 5
    do 
        # random
        echo $amount.noDupli.random.$t 
        { time ./useIntList < tests/$amount.noDupli.random.$t>  /dev/null ; } 2>&1 |  cat > tests/time/useIntList.$amount.noDupli.random.$t
        # sorted
        echo $amount.noDupli.sorted.$t
        { time ./useIntList < tests/$amount.noDupli.sorted.$t>  /dev/null ; } 2>&1 |  cat > tests/time/useIntList.$amount.noDupli.sorted.$t
        # reverse
        echo $amount.noDupli.reverse.$t
        { time ./useIntList < tests/$amount.noDupli.reverse.$t>  /dev/null ; } 2>&1 |  cat > tests/time/useIntList.$amount.noDupli.reverse.$t
        # random
        echo $amount.duplicates.random.$t
        { time ./useIntList < tests/$amount.duplicates.random.$t > /dev/null ; } 2>&1 |  cat > tests/time/useIntList.$amount.duplicates.random.$t
        # sorted
        echo $amount.duplicates.sorted.$t
        { time ./useIntList < tests/$amount.duplicates.sorted.$t > /dev/null ; } 2>&1 |  cat > tests/time/useIntList.$amount.duplicates.sorted.$t
        # reverse
        echo $amount.duplicates.reverse.$t
        { time ./useIntList < tests/$amount.duplicates.reverse.$t > /dev/null ; } 2>&1 |  cat > tests/time/useIntList.$amount.duplicates.reverse.$t
    done
done
echo ===Generate Done====